<script setup>
// Styling settings
const stylingSettings = reactive({
  width: 50,
  colors: {
    A: "#22cc22", // Green (Vivid, slightly off pure green)
    C: "#3366ff", // Blue (Bright, slightly softer than pure blue)
    G: "#222222", // Black (Deep, not pure black)
    T: "#ff3333", // Red (Vivid, slightly softer than pure red)
    N: "#bbbbbb", // Gray (Neutral, light gray)
  },
});

// DNA input
const rawDnaCode = ref("");

// Computed property with getter and setter to handle filtering and uppercase conversion
const dnaCode = computed({
  get: () => rawDnaCode.value,
  set: (value) => {
    // Filter to keep only A, C, T, G and convert to uppercase
    rawDnaCode.value = value
      .toUpperCase()
      .split("")
      .filter((char) => ["A", "C", "T", "G", "N"].includes(char))
      .join("");
  },
});

// Prevent non-DNA characters from being entered
function onKeyDown(event) {
  // Allow navigation keys, deletion keys, etc.
  if (
    event.ctrlKey ||
    event.metaKey ||
    ["Backspace", "Delete", "ArrowLeft", "ArrowRight", "Tab", "Enter"].includes(
      event.key
    )
  ) {
    return;
  }

  // Check if the key is a valid DNA character (case insensitive)
  const key = event.key.toUpperCase();
  if (!["A", "C", "T", "G", "N"].includes(key)) {
    event.preventDefault();
  }
}

const sampleDNA = ref({
  cats: "ATGNNGNNNNCNNNGNNNNNNNNNTGNNNNNGGNNNNNNNNCATTNGNNCNNNAANGGNTNTGNCCANNNCNGGNATCTCACCAAAATATATGAGGAAAAGTCCAGCACTTTCTCTAGAAGTTCAAATACTCTCAGNAGGTAAAAAAATTAAAGTGANNAGGACNGNNANNNNGCNNNCCTNNANGNGNCTCNNNTTGAANCCNNNANCNNNATGCTTGTGGCCCAGTCAAAGGCCAGTGTTCCACCAGGACAGAAAGTGGCCTACAGAAATGCTCTTAAAGTGGCACTGGAGATCCTGAATAAGAGAGCAAATTTCGGTCCAGCAAGANCNNCNNNTGGNCNANNGNNCACNNCACCNTNTNNNNNNNNNCCNCTACCTGACTGTCCCCGGACAGGTGCAGAACGGTTTCTTCCCCACCCATTTGAAATGCAAGCTCGTAAAAAGTACCGGAAGCCTAAAGGTACCTTACTGAGGAGTCTTAGGAAAAGAAAAAACCTCAAANCNCTGCNGNTNNNNNNNNANNATNNNNNCANNNCANNCNNNGNNNNNNTNNNNNNNNNNGNGNNNNNNNCNANNNTNNNNNNNCNANGGGNANNNCGNGNNANNNNCNCNNGGNNCNNNNGNNNGTNNNNNNNNNNNNTCNNNNTNNCNNNNNNCTNNTNCTGGCCCAACGAGAGACAACGAGGGCGCTCATGCTCCNAGNNGNTNNTNAGNCNNGNGNCCNACNNCNCGNANNNACANTGGCCNCNNNTACTCTANNNNTGTTTGCACTCACAAGGTGCAGGAGAGCTGTCTGTACCTGGGAAGACACCTTGGGATGGCGCCACCTCGGAGGAAGCGCATGNGNANNGCNNNNAANGNCCTNGNNNNGNNNCNGNNTNTGCTNAAAGTTCTCATCACTTTCGGAAGATGTTCATANNACANGNGGCCGNCCACANGNGCNCNNNNNGNNNNNGNNCANNNNNNNGNNNNCNNNNNNNNNNNNGNNANNANNGNCCTNNNNANNGNNNATNCNGTNNCANCGCNNNAGNNGTNTNNNCTCTNGNNNNGNNNNNNTCNNCNTNNNNNNNNNNNTGGCGGTCACGCAGGCCCNNNNNNNNNNANGCTNNNTCCGNNNANACNNNNNNNNCGNNNAATGGATGAAATCNACNGNCCTATGNATNNNNTNCTNCNNGNACNNNNNTNAGGTCNNTACTNGNNCNNNGNNAGNNANGNNNNNNNGNNGCTGCNNGNNNNNNCTNNNAGNNCATCACTCATCACTTTCAGAACATGATCATAAGACAGGAGGTCAACCACACGTGCACACAACGGTCACACGCACTCTAAAGGAAAGGNNAGCANANTCNNCNCNAANCTNCANCNNNTNCNNNNNNTNCTNNNCACNTTCGGAAGATGTTCATAAGACAGGAGGCCGACCACACATGCACNNNACGGTCNNNNGCNCTCNNANGGANANNNNNCCNNNCNAANNCNNNNCNNNNTNTNNNNCTNNNNGNAGCNTGTNNCNGNGCNGCNNNNAGNTTCATTNATNNNCNNNNNNNNNNGNNGANNANANGNNGNAGNNNNCCANNCNNNNNACANGCNNAGCNNANNNNTNNNNNNNNCANNANGNNNNANGNGAGCAANNNCNNNNNNANNNNNCNNCNTNNGNNNNGNGNNTNTTACAACCTTGTTCANNNCNNTNNNNNNNCNTNCNGNAGANNNCCANNNGANNNNNCTCTCGGCNNNNNNCNNNTNCNCNNNNCNNNNNNNCNNNCTGNNNNNNGTGCNCGCCNGGNNNAACCTNNNNGANNGGCNGGNNNANNCNNNGNNNANCTNNACATTTGCACACACGNNTGNNNTCAANGNNNNNTNTCCATNNCNAGGNNNNGNAGNNGANCATANGNCAGGANGCCGACCNCACGTGCACACAACGGTCACGCGTACACTAAGGGAAAGGCGAGCAAAGTCCTCGCGAAGCTGCAGCGTGTGCTCAAAGTTTCCATCGCTTTCAGAAGATGATCATAAGACAGGAGGCCGACCACACGCGCACACAACGGTCACGCGTACACTAAGGGAAAGGCGAGCAAAGTCCTCGCGAAGCTGCAGCGTGTGCTCAANNNTNNCANNANTTNCNNCNANGANNNTGANNNNNNNANAGGAGGTCAACCACACGCACACGCAACGGTCACGTGTACTCTAAAGGAAAGGCGAGCAAAGTCCTCGCGAAGCTGCAGTGTGTCCTCAAAGTTCCCATCACTTTCAGAAGATGATCATAAGACAGGAGGCAAAGGAAATAGGGACACATCAAGAGGTATGTCTTTGCATCGCACAGTCAAAGAGAAGGGTACAAGTGCTAAAGATGGAGGCATNCTTCCACCNTTGTCANTGNNNNNNNCANNNTNNCAGGTATACCTTTCCTAACAGGNANGNNNNNNANNNAGCNCTAATCATNGANNNANANNANGNNNNTNNNNCCNNNNCNANNNCCCNNGCNNTNNNNTNTNNANNCNNNNCCNNNNNNGNGANNNTNNTNAATTNNNCGANNNATNCCNTNCGGNCNANGNNNNGNNNNANCANTANTAGCCTNGAAGCNAGNCNTGGAAGNTGCAGCAGCANCCTCCANTGCCCCTAAACAGAGGCGGTGTTATTCACTCGGTCTGGCAAATAGAAAAAGGAAGCTGCAGGTGACAGAGTTTGAGAAAGGGCTGCAAGAACTTCAACCTTCAGTCAACTCAAAGGCTATTAACCCCACCACCCCTATTAAAAAGAATGCCAACAAAGAAATGGGACAAGTGGCAAGCATGGGTTTTCCACAAGAGCCTTGTCCCATTGAAGGAGGAATGATGGTCTGGTTCAAATTTCAGGATCACCCATTTTGNCCTGNNNNANNNAAGAGNNNNAGNCNNNNNGNNNNGACNGCAANNNTNNTNNNGNTNNNGNCAANNCNCANNNCNNNCNTNCNNNNNNNAATNAGTGGCNTTCGCCGTGACTATCGCAGTTCCTCTTCGAANATTNANNNNNNNNNNTNNTANAGAGNANGNAANACTNANANAGNGAGCCAGGAAATTGTACGAGCAAANTNTGAACTGGTNNNTCNCCNTNNNNNCCNNCTNCANNGANAGCCNCNGNCNNGNTNCTNNTGNAGGCAGTTTCCTGGACTATTATGCTGCTGACATCAGTTACCCAATTAGGAAAGCCATCCAAGACAGGGANNNNNNGNNNGNNTTCCCNNNNNNGNNNNNNGNNNNCCTNGNNGNNNNNNAGGCCTAAGNNNNNNCCNNNNNGGACGGGNANNGNCCNNNCNANAANANTNCCNNNNNNNNNNCCNNNNNCNGATNAAGGNNGCTCANNNCCNNNCCNACCNNAANCTANTGGACTTCANCGTGAAAACAAAGGGGGCCGATCACCATCTTCTGGACATTGTCCAAGGCAGGAAACAGTCCAGGTGGCTGGTATCATTTAGGAATTCGAGCAGGTACGTGATCTGCGTTGAAACATACCTGGAGGACGAAGACNAGTTGGNNANTGTNGNAANNNATNTACAAGAAATCTACAAACAAATAGACAAGAAAACGCTGAATCTGGNAAGGNNTGNCANNNTGAGTNTTGNTCNGGNAGNTCTTCTGCCAGAAGCAATCATTTGTTCAATTNCTGCNNTTNATGGATTGGATTACAAGGAGGCAGAAAAAAAGTACCTACAGGGGCCACCTGTGCATTACCGGGAAAAAGAGCTATTTGATAAAAATATCCTAAAGAAAATAAGAAAGAGATAANNNNNNN",
  dogs: "ATGTTTCAAATTCCTGTCTCCACTAGTGATTTATATAATCGGAAAATCTTGACAACATCAGGAAGGTACGAAAAAAGGTGAAAGGTCTAATCATTCTTGTGGATATTGGGCTTGACAGCTGCAAGCCTACTTGGGAGAATTGCTGAAGGACCTTAAAGGCTTTCTTCACGACCCAGGAGAGAAGTACTTTTTTAACACATCGTGGGGAGATATTTCTCTCTGGGAACCTTCTGGAAAGAAAGTGAGATATCGAACTNAAAAGCCATACTGTTGTAGCCTCTGTAAATACTCTACAAAAGTGCTTACTTCATTCAAAAATCATTTACATCGNATTACCATGAAGACGAAATTGATCAGGAGCTGGTGATCCCTTGCCAGACTCTAATGGCAAACTGTGTGTTTTCTTCTCAACCCAAAACTGTGGCCAAGGTCTATGATGTGAGGCAGGGTAAGGATGAGAGTCCAGAAGGCACTTCAGAATGTTTCATGCACCTGTTCGGAAAGTCCAGAACTACGAACCCAGAAGCCCCGGAAACAAAGACAGTAAATATTTTAGCTTTTGTTAACCAGGCCACTCCAGATAGTGAAACGAAATTACTAGGAGTGATGTGANTAAGAGATAAGATTTTACATGTTTAAAATGTAACTTTTCAAACACTTTGTACTAATAGAGAAAGTCTGGAAGAACAGCATGAAGAAGCATGTGACTGGTAGCCCTGAAATATTTTCACTACTTAATTAACTCCTACTTTGGCCTGCGAACTGAGGAAATGGGTGAGCAACCCAAAACTGGCTCCAGGGACAGGTAAGGAGGATAGCCTTGNTCTACTGCAGAAGATGCCACCATCTGACAAGTATCCNANNCNCNTATTGTAAAAAGGAGGGCCATTGGTTAAAAAGCTGCCCTAATGCAATGCCAATGCCAGCAGCCAGGATGGCTTTAATGTATCATATTTTGACATCAGACATACACAGGGATTTGGAGAATAAACTTAGGTCCGTGATTTCAGAACAACTATTAAGATGGAGGGGCAACCTGGACTTTTGAAGTCCAAATGCACATTGCTCCAAAACCAGCAGCGCCTTTGGCTGCACCACCAAACAGCAGCGCTCCAGGCATCACAGCCACATCCCCTTGCTTTCGTCTTGCCTTGNNCACCACAGAATGGTCAGAGCCAGACCATGGTCCAGCCAGTGACTGTGGCCTCAGGCACGATCTGGAAGCCTCACGCACTCTCCGCCTGCTGTGGTGCAGTCCCACGTGACTCTAGTCTCCAGTCCTCTCCCTCCCTCTGCTCCCCAANNGGGGGGCCCTGTCTTTCTTTCTCATTGAGGAGTCCCACTTACTCAGTCAGCAAANNNNTCCGATTCCTGTGTTGCCCTTGAGTCAGCCAGTTGGANATTGTCNCCTATAAATAAGTCTGTTGGAACTGGTGTCCTCCCTCTAAACCAGACCATCCGCCCTGGAGCTTTACCCCTTAGCCAGCCTGTTGGGCCTGGCGTTCTTTCAGTCAGCAGACCTGCTGGGCCTGGCGTCCTTCCTGTCAGTCCCTCGGTCACCCCTGGGGTTCTTCAGGCCGTCTANANANNNCTAAAACCAGGGGTCATTTCTGTGAGTAGGAAGGATTTTAGCTGTCCCGTCAGGGGTCNNNGCTTCCTGCAGGCCAGATGACCCCTGCTGGGGTTATCCCTTCAGGACAGACGGCGACTTCTGGGGTTCTTCCTGCTAAGGCCAGGTGGTCCAGTCAGGGGTTCTCCCCATTGGCCAAACGGCCCCATCAGGGGTTCTCCCCACTGGGCTGACAGTCCCGTCCCGGGTTCTCCCTCCTGGCCAGACGGTACCACTGAGGGTGCTGAACCTGCAGGCCAGGTGGTCGCTGCCTGGGGTCCCAAACACATACACCCTCCTCTCCTTTCTCCCACCAGACNANNNNNNGNANNCAGTATCAGTATCATCAGGTGTCCTTTTCAGCCTGCCCTGTGAACCAGGGTATTAATTCTGGTGTTCTTCAGCTTAGCCAGCCTGTCATGTCAGGAGTGCTCCCCGTAGGCCAGCCAGTTAGGCCTGGGGTCCTACATACTTAATCAGTCTGTGAGCACCAACATCCTGCCTGCAAGTCAGCCTTACACAAAAGTTAGGCCTGGTGCTTCTCAGAACACCACCTTCCTCACGTCGGGCTCTATTCTCAGANNCAGCTCATCCCTACAGGGAAGCAGGTGAACGGGATTCCCACGTATACCCTTGCCCCTGTGTCTGTCACTTTGCCTGTGCCTCCGGGTGGTATGGCAGCTGTCCCTCCCTCCCAGATGCCCAGAACAGAGTCCAGCTCCTGCCTTCGGGCCCAGCTGCACAGATGGCCAGTTCTGTGGCCAGCATGCCCTCCCCTCCGGTGCTCGTCAGTGCCACTCAGAGTGTGTTTGTTCAGGCCTCTCCGTCTGTGGTAGAGGCGAACCAGGCACTCAAACAAGCGAAGCAATGGAAAACCTGTCCAGTTTGCAATGAGCTCTTCCCTTCCAACGTCTACCAGGTTCATGNATGGAAGTGGCTCATAAGCACAGTGAGTCCAAATCTGCTGGGGCAGCCAAAANACTGGAGCCTGAAAAGCTGGCAGCATGTGCACCATTTTTAAAGTGGATGACCATGGGGGAGAGAAAACAGTTCGGTGTCTNCTCTTGTAAATGCTTAGTGTCCGAGGAAGAGCTCATCCATGGAGCACTTGCTAATGCACGGCCTGGGGTGCCTGTTCTGTCAGCAGAGGCGTGCACTTTCCATGACATTAAAGGTCTTTATCACAGAGCACAGCAGGACTATCTGGGCACCGGGGAAAGAAGAAGTTACCTTGGTGGACTATAGTAACAAAGGTCAGACATTCCAGTTGGATGTCGATGCCAATGGCAACCTGATGTTTCCCCACATCTTGATTTCATTACCATTCTGCCAAAGGAAGAGTCCCTTGGGGAGCGGGAGGTCTTANATTTGGCAATACTCAATCCGGGGGCTGGGATCCACTCCAAGTCCCTGGTCCCCGTGTTATATTAACTTACACTGAGTGAGACCCCAGNNTGGGAGAGGGTGCCTCCGGGANGCCCTGGCAAACAAGCACTGACTTGCCCCTTTTGTCATTTGGCACCTTCGTGACGACTGAACTGGGCTTATGACGGTTCATTTGAAACGCATCGGAGTACTCACACGGGAACAGGGGAGAGGCACCACATCACGCGACATGCAACGGTCCACACCANNNNTTCTCGAGCAAAGATCGAGCAGATCGTGGAAATCCCCAGCGTATGCCAATTATCAAATGCATCCACTGCTGTGGAGTCTACACTGGCAACATGACCCTGGCAGCCATTGCCATACACCTGCTGCGCTGCAGAAGTGCTCCAAAGGACAGCAGCTCAGACCTCCAGATCCAGGTATTTACTAGTGTTTGTCCTAATTTTATTGAGANGNACAGCGAAGTTTCCCAATGAAACGGCTCTTATNGTGNCNANGNANCTGAATGGTGAGGTGGTCCATGACACTAGTTTTTCTGTAAAGAGAAAGTTGCCCGATGGCCACTTCGGGACAGAAGACCAGAGGGATGCAGAGGAGCGGCCTCTNTGTTATTAGCAGATTGGAAATTACATGATGCAGATAGGCCCCTGGCTCCTGAAAAGGTGGCAAGTGTGGACTGCCTTTTAAAAGACAGAGGAATGAAATCAGGACAGAGGGGGGGCCGGCTGGTTAATGATGACGCTCTTCAGATTTTAGCATTAAACCCTAAAAAATATGAAGACCGTTCTTATGAAGAGAAAAAGCAATTTCTTAGAGATTATGTTCGGTCTTCCACAAGAGACCATATCCTAGTAAAAACCTGAGGTGCTTGAGGAAATAGANNNNCANNAACTTCTTTCTTCACTCATANNNNTNACAANNNNNNNANNTGTGGGTGTGGCCTAAACTGAGGGCCCTCTATGAGACTGGGCCACCCCCGGACCCCTATCGATGTGGCTTCATTTTTTGGGAAAATGTGAAGATATATTTGCACCAGACACTTCAACCTCGCTGAAAGCAATAAAAAATCACAAGCCTTNNNNNNCNCACTGTACTTTTAGGCTTTGATCAAGAAAGAAGNGNNTNAATGTCTGACACTTAAAAATGTTAAACACAGCCNGTTGAACTTTGAGTATGAGCCACAAAACTTGTAACAGAATAA",
  apples:
    "ATGAGTAATCGTACCCTCCCTCTCCAGAAAAGTCGATCCCTGAACATGGCNACAGGNNNNANNNGNNGNNNNNNCAGNNNNNNNNACCGNTNGTNNNNNGACCCCAAACCCGAAGTCATAAACGGTGTCGTTTATCGTCCTAGTGAGAGTGATAGGAGCAGCAGCAGCCGGGTGCCGTGCCAAGAAGTCGTACGAGTACGCCAAGGCAGAAGGGACTCAATNGNNGNNGNNTTGCTGCAANGANNNNCNANGCTGGCGNNGNCNNNNATTCGAATTNANGNNATGGAAGNAGNNGGNNNNGNNNNNNTNCANNANNGNNNNGGACGCAGAGGCCCTCAAGTGGCTAAACATCGACTACGATCTTTCCATCAAGTACTTGTCCCAAAGCCACTGCCTCCCCGCCTGTCAGTCACTTGGCGAGCTCTATCTTNNCCNTNNNNNTNNNNNANNNNCNNNNNNNNNNCNNNNNNNNNATTNANNNCTNNNNNNNNATTCATAACCTCTCATTTGCAACCAACGNNNCAGTCNAGCAACAGGNAGNNGACAANGCATCNNNNTNNCNTNTTGGCTCCCAAATCGCAACACCCTCAGGCCAAGTGCAAGCTACGATTATGAATNGGNACAAATGTTTNNGNNNNCNNNGACNTCNAGGTGGAGGCGGAGGATGTGTGAGTGATTTATCTAATTCCCTTTNCNACNCTNGNTCCGNTAANANGGTNAATATATCNCNNNANNNTNTNNTCANGNNGANNNNATTGCTTNNANTCCANNNCGNTNNNANTGNTCNNNCCNAGATNNNNNNTTTTGNNNTTAANANTNNNGCNNNNNTNNNNNGNNNTCNNTTNATNATNNNNAAGACTGTNNNANNNNANNNNANANNTNNNNNNGNATATGCNAGGACCAAANTACTGGCAANNNNNNNNNNNNNNNNNGNNGCNNNNNGNNCTNNTNNTANNNTTNAACCTTCATCAATCAAGTTCCATACAGCAGGAGGTAGATCTANNTGNNTTNCTNCNNNNNCAANACCNCNNNCNNGGAGTCTACTTGGTGACCCAGAGTTGGGAAATGTCACTCAAGAAATTCCAATGAGGCCAATGCAGGTGCCTTGGNTTTNGCATNNTNTNNNGGTANNCNNNNNGANAGNCNNNCNNNNNTTTNNNANNTGANGAAGANTNNNNNNNNNTNANNGNNNNNTNCNNNNNCTCNANTGCAACCATTGCCTAATCAATTGCGGTCATCTGATATNNGTNCGGGTACTAACCTGATTACTCAATTCGATGGTGTTAGCAATGGGNCTNNTNCNAGTNTNANCNANNTGTNNNNTNNTCNGCAGGATTGNNGAGNGNTNNNNCGATGCTNCTNGAGAGCNCCNANCACATGTGGTGCTGCTGCTGGTGTGGCTGCTGCATTTCGTGCCCCAGTTGGTGGTGTTCTGTTTGCTCTTGAGGAAGCAGCTTCGTGGTGGCGGAGTGCTNTACAGTAGAAGACANTTTTCAGGGAAATGGTATTGATTTGAGGACTAATCATGTTGGAATGCCACCAGCCACGCCATTGTTTGATATTTCAAATGCTGTTGGCACACCAGCTACGAATAATACANAGNTNACTNNTNTNAAGNGNANNTTGNNAANAANTNGAACTTCTCCATTCAAGGCTTCTCCATCTCCACTGCAACCATTGTCTAATCAATTGTGGTCGTCAACTATAAGTTCGGGTACTAACCTCATTACCCAATTCGATGGTGTTAGCAATGAAACTGCTTCTAGGTCAAACAGTGAGTTACCTTATCGGCAGAATCCCCTTAGCAGGACCCACAATACAGTAGAAAACAATTGTTTGGCAAGTGCCATNGNCNNNGNTTTTGAGAGNNNNTNNNGNNGNNNGNCNACTGCCNNNGNCANNGGTNGANNTGNCAAATACTGTTGGACCANCGGNNAAGNNAANCTTGTTNATTCTGAACAGATCACTGGTGTAAAGAGGAGGTTGGGAAGAAGTTCTNNNNNNNCATTNANNCNNTGNNGCNCANNCTNCTTANNNCCNANNCNNNCAATTCATTCTGTTATTCCTAGGAACTGTTGGAGNNANTCCANGACTACTTAGTAGCANNNANNNNNNTCCCTTNCNNNANNNGANTCANTTANNCCTANCGGNGTGTCTACATTGTCCTTNGATCANTNNNNNTNCNAAAGAAGGGTTTCTACACGATATCCTTCACCCGTGACTAGAATGTATGTGAAGAAATACTTTGGAATGCCGCGACCTGACCAGAGCATGGTGATTTATATCGCGACAGCTATAAACGGTTCNTNNNTCNGANNNNNTNANANNAATNACCGCANCTNANGANGNCNANTNNATGNCTNNTCATGAGTCTGGCTTAAACTGCATAGGAGCAGGANNNNNNNTCNNNNTNNNNNNCTNNNATGGAGCTTCAATGCAATATACCTCCAGAGAGTGGGTCACAAATCATTACAAGTGGGTTGTCTGGAAACTGGCTTGCTATGAGAGATATTATCCAGCTAACTNTTTTGCAAAANNCNNNANNTNCTNCNNCNNNNTCAGATTTGACAAGATGCTTCCGGCGAGGANNNNNANNNTNGTNATNNAGAAATGGTGAATCATGGTCACCGGTCCGNAATGGAGANNNCCTTTCTGGAANNNNGTNNANNACCTNNNTNNCNGNNGNTTNTATGTNNTCGAGNTNTTNNNNNNNTTTGNNACCCAAATATGGANNCTGCCCTTGTNCCGGAGCTGAANATAGTNNTNNGGCATGCTGTTTCCCGTCCCATTTTTCTTTCTNNTGCTNNTNNNNNNNNNCNNNNNNNNCNNGTNNTNTNANNTNNNNNNNNCNANGNNNNNNTNNNTNNNNNNNTGNNNGNNNCNNNNNNNNNNNNNNNNNNNNNTNTNNNNGNTNNACTAGNANNNNNNTCCTNNNTGGGNNNCCNAANGGATNGAATNTCAATTGATGTAGAGGCTGGAACACTNANNNNTGNNNNTTNTNCAGTGGATGCTGTTCTCGATGCACTCCTGTCAAAGCAGCTTGCTAGCGGAAAATTGTTTGTTGGACAGAAGCTTCGGATCTGGGGAGCAGCACTCAGTGGCTGGGCTGGGCCTGTTTGANNNCANNANNNNNNTTGGGTNNCNNAGCCCNGCCCCTCNNNNNNTCAAGACAGATTNTTCTGNANCNACTGCAAATTCAAATGACATNGNNNATANCNNCNNNGANNNNATNCTCNNCNGGGGTTCCTCCTTCTCTGGCCAGCATCGNNANAGAAAAAGNNNNNCCTTNTNGNGNNGATCNATTGNAGAANGNTNNNTNNGGTGGATGGAATCAGAAGCGCTTGATAAAACTATACACCAATNNGTNAANGNNGNTNTNNNNNNNGNNCNATATGAAAGTGCTTATGAAACTATACGATCAGGAGGTAAATGCTGACGTTGCTGTGTCTGGNTGTGTTTCCNNNGNNTNTNNNNNAACNNANAGNNGNNGNGNNNNAGNNNCNTNNANNNNNNTNGNANTNNNANNNNTNTNNCNNNNTNTNTNNNNNNANAGNNNNANNNANNNGCTGCAGGAAATNTTTCANGANTNNNNNNNNTNNNGNNNAAGGTTGGATATACACTGCAACCTATTTGGTCCAACTGCTTTGCTCCAGATATGTGAATGCCCTGTGCTCGCTGNTTNNTTGGANGTGCTAAATATATCCGAGAACCCTCTCACTGATGCATGCGCATCTTATCTTTTAGATGTCTTGGAAAAGTGCAAGACCCTTTACAGCTTGANNNNNNANNGNTNNNNTATNANNNCTACAANNNNNCATGTNGGTTNTATTGTACATAATGCTCNTNNTCCANNNNNNNTANNNTNANTNGGATNTNNNTANNGNNANNGNTNGNTTAGNNNCCNAAATGGTGAAGTTACTNCAGACAGCAGCTGAACCTGAAATTTTAATGGCAGANGNTNGTNTNNNANNNANGNNNTNNTCTCTGAAAAGATTTTCACGTTTGAATCTGAACGGTTTGGAGCTAAACAAGCGTGCAGTTGATAGCCTTTGCGGCCTTGCTTCGACCTTGCCCTTGTTCGANCNAATNNNNNGNNAANCTNGNNNNNNTNNNCCAGTGAGATNNNGNGNATCNAAATCATTTTTCCATGATNANNNGNNAANGTCAGCNNNNNTGAAGCAGAAGTCACGCCATTCATGAGAGTGAGGGTGGTTGGACTAACAAGAAAATTATACCAAGGGAAAGACTGTTCCAAAGAAGGCTTAATAACAATCTGGAACCCATCTGAGAAACAGAACTCTGAGCTGGTCGAGGGATGTGCATATAGCATTTCTGGACTTATACCAACAAGTTCTGATGGAGNNNTTCCAAATGGAGGATCTTACTNTTGANNAGNNGNNNAACAACAAAATGGCAGCCTTTATCTCAGCAGGCAATAAACTACTTCGAGCCATTTTTCAGTCCTCGNGNATNNGTNTNNTNNTCNNNNTNNTATTACANACNNCTCTCCANAGNAANTNTTNNNGACNAANNCNNNTTNNANNNNNNNNNNNNTNNTNCAGCCCCTCGCAGNTATGNNNNGCAGCNTNTANGANNNAAATTNNTTAGAAGATGATATCAAGGAAGAGNNTNGCANANNNTNANNNNNGANNNNCTTNANTACCAGTTATTANAGNTGTNNNNNNNNNNNNNNNNTNNAGAAGNACNGGNAGNNNNNGNNNNNNNNNNGNGAAAANGTTGTATCACTNNNTGCNNNNNNTNNNNNNNTNTNNANNNNNNATTNNNANNATCTCAAATGCTCCTATAAACTATAACCTCACAGGATCTACGGTTGGGTTTTGTAATCTGACCAAGAGAGAAAAGGATGAAATGAATTGCCTTTGGGTAGCTGAATATCNGTGANAGGAAGATCCNTCNNAANCNTNNNANNGNACANNTGTTNCNTANNNNAANNANNNNNNNTNNNCNANCNAAAGATGGAAAAGGATGTCTATCCTGACTATCAATAGGCTANCNNTNNNNGTTNNAGAAAANATNANNNNAAANNNNTGA",
  humans:
    "ATGNNGNCGGTCANNNAGGAGNNNNCNGGCCGCGAGGACCTGGCCCTGGCTCTGGCCACGTTCCACCCGACCCTGGCCGCGCTGCCGCTGCCGCCGCTGCCAGGCTACCTGGCGCCACTGCCCGCGGCGGCCNNCCTNNCNCNGNCCGCNTCNCTGATGGAGNGANNCGNCGNTTNCGAGNNNCNGCTGGNNCAGCNGNCNNNGGACGNGNNCNNAGNNNNNNNCTNAGCCNCNNGGGCCNCNACCTCAGCCTGCACGAGNGNGNCCCNCANCTCCNCCTNCNCAGNGNCCCGNNNNNCNNCNNNCGCTNNNTGGNNNCNGANNNNNCNNGNNTNCNGGCCGCCAGGCCTGANNCNNTCCGCTNCTGNANNNCGGCNNGCCGTGNCCNTNNGNCCNGCNTGCGNCNGCGNNGCCNCGCTGCTCTACGNGCACAANCTNTGCNACANCNTCCNGNNCNNGGNCATCCGCCACCGCGGCGAGTGGCTCACGCCCAACGAGTTCCAGTTCGTCAGCGGCCGCGAGACGGCCAAGGACTGGAAGCGCAGCATCCGCCACAAAGGGAAAAGTCTGAAGACGCTTANTNCCNNGGAGATCCGTGNGCANNAANNGGNAGNCNNNGNCNGCTGNCCTNCNGCAGCCCCTNCTNCNCTGAGGAGGAAGAGANGCTNTNTTCNNNNNTGNNNTNNGNGCGCCGGCTGGCAGACAAGAGGACAGTCGCCCNGCCNGNCNCACGNAACCNCTGCNGGANANNAGTGAGGAGGACCCTCANGCGNNNCNNGGNCCAGCTGNTGNCAGTTTNCCNACTGTGNTNACNGCGACNAGANTGTCCCCACCNGTGGGCGNCGGCCGCNANGNNTGNGAGATGGAAGCACTCTGCAGGAGNATNNCCCNCNCTTANNCNGTCNCNTGNAGCTGAATGGCGNNNNNGACGCNNNCTGCAAGGGCTNTTTCTAGCTGAGNNANNTCNNNCTCTCCTNCNGCNNGGNNNNCCGNGGCCAGGACGGCAANNTNCCNANNCNCANTNNTNNAGNNNCCTNCNNCNTCAANGNCNCCACCTCGTTATGCCCGAGCATCANAGGNNCGTGCNGCAGCNCTCCGNNGACGNNGCCAGCTGGCCACAGANNNNCNGCAGGNGNNTNNGACCNNGCCTGGGCATCTCCTCTCCTGCAGCGCCGNCTGNNNCCNNTNNAGNANGCGNCTNTNTGTGNNNGNCNGNNCTCCCCGNGTCCNCAGGNCCNNNNCCNTTCAGAGAAGAGGGCACGAAGCGAATGNNCTCAGGTCTGNGCACCCCNNCTNCCNGGTTCTGGANCTGGNCNCNAGCATGGCCCCGGAGGACCNNGACNGCCNGNNCGTGCCNNCAGNGGNGGAGGNCNACNNAGNCNTCCTNNGNNGGCCCTCAGNGNTGGTGNNCTACNACNTGGNCCTCCCCAGCCACGGTGAGGACCCACCCTGGCATGATCCCCCTCATCACNTCCGCAGGCNGCATNNCNCANNGCTCATGNAGNAGGTGGCGGCTGCAGCTGTGNGNGGCTNCCCTNGACTGNGCNGCCCACCTGNCTTCNTNCNCGGCCGCGANGTNGGTGNCGAGAGCAGGGCCTGGCTCAGCACNGGGANGGCNCNGCTCATANCCTGCAGCGCCGCCTGCTGGCNNCNGNNANNTCNNTNNCNCGNNGNTGAAGCCCTGNNNNTNNNCTCTCCTGCAGCGCCACCNNCTGCCCNCCTTGCTNTCGGTTTCAAGCAGAGGGNCCNGNNNNNNCNCNTNGTCCTGNGCCCAACNTCTCNNGCCNCNCTNCCTGNNGNNCNGNANGTNCCCGGCNCTGNGNGGGNCGCCNGGCNTNNNCTTCTNGCTGTNGGGGCCTCTCCAGGAGCCTGGGGTGTGGCCCAGCAGTGGGATCCACTCACGAGTCNCGCANGCNGNNCTGNNCNCNTGCGCAGCGNCNGGANCTCCNGCGGAAGGAGAACCTGGCCCGGNNNTNNCTGTTNGCNGACCTCCTGCATCNACGGNAACTGNNNGCAGAGAACCCGCNTNCGNCNNNNNCNNNGNCNGGGCANCTCCTCTCCTGCAGCGNCNCGTGGTGTGGCCNCNATGNCCNCGCGCNGTNGCCCGNNNGGNNGNGGCNGCGGTGNTGNCTGGTGCCGAGAGCNGCNCNGGGCCCTACNGGTTCTNTCAAGCTCATCCCCACTGCCCNCTGTGGNCGGNNNTGANNGCTGGCCCTGCGACCTCAGNGGCCCCCGGGCTCCGGACCNCCCACCCCGTCCTGGGNATNTCGNGGNGTCNGACNANCCCCNCNNCCCGNANGGGNNGTNCCGNNACTNCCTTTAGTNCANNTNGCNGNCCANGGNGGGCTGCTCCTCCNTGCCNNNACAGNGGNCCAGGCNAGNCTNNCTGGGAGCCTGTGGNNACNTTNNTCNNANNNCTAATCTCCNNNGTNNTCNNCCNGTGGGTGAGGNTATNNCGNGGCGGCCTGGTGGATCNNCTGNNNGGANNGTGNNGANCACTCCGNNCCNNNGNCCGGNNNGNGGACGTCCGTCGCTGCCNNGNGCACCCGNAGGNGNTTNNTCCNAGNGNCCNNNCTCCGTTTCCAGAATCNCNCNTGNANCTGACCCAGCTGCACAGGCTGAGCCTGGAGAGCAGCCCAGATGCCCCTGACCACACTTCGGAAACATCACANTATGCTGTNGGCNNCTACGACAGCNCNNCACACCACCCGCCACCTCCCGGCGCGGTAGGGGGACTCNCNGGCNACNGGANGGAGANGNNNNAGCNCCNTGNGNACGTNNNCAAGTGGNCCGTGGCNNACNTCCTCAAGCCGACNCCGTTNNGNNCNTNTGNCCNTNCNTGNNTGTGGAGAGTANNCNCGGNCNTNGCAGGNGGCANNGANNGCNNNNGNNNNCCCNACNNNNCNGANGGANNAGTNNNTGCNNNCCAANNNNNGNNNCCTGNNNNNGNGNNNCGCCCNNNNANATCCGGGCNCAGNCAGGNNNNNGCNTGNGCTNNNNNNNATNCANGNCTCACNNCTTNTCTGNNNNTNNGCCANGGNAGGTGGCTGACAGGAAGGATGAGGACAGGAAGCAATTTAAAGACCNCCCGAACCCNGNNNGCTNCNNCNNCNACTCCATNNAGGANTTCTCGGAGAGAGGGATACTGAGGCCCCTGAGCACTCGGCATGGGGTGGAAGACGATGAAGAGGACGAGGAGGANGNANANNNGNGCAGCNNNNGNCCCCCACGNNGGCCNCNNCTGGGCNNCNNNNNCNNNNGNCGCNNCNNTGNNGGTNNNNCNNNNCNCNNAGNANCAGGAGANTNNNNCGCNGCCNNNNNCNNNNANNCNGCCNGNGNTGCTCACCNTNCANNAGNCTCTNTGCAGTGGATNTGA",
  none: "",
});

// Sample DNA Selection
const activeSample = ref("none");
function activateSample(sampleName) {
  if (activeSample.value === sampleName) {
    activeSample.value = "none";
  } else {
    activeSample.value = sampleName;
  }

  rawDnaCode.value = sampleDNA.value[activeSample.value];
}
</script>

<template>
  <div class="w-full flex justify-center items-center flex-col">
    <div class="w-[80%] mt-10 flex flex-col justify-center items-center">
      <div>
        <div class="mb-10">
          <h1 class="text-center text-5xl font-bold">DNA Barcoder</h1>
          <p class="text-center">
            Visualize DNA Nucleotides through a colorful barcode
          </p>
        </div>
      </div>

      <div class="w-[80%] flex flex-col gap-y-10 justify-center items-center">
        <!-- Select an example -->
        <div class="w-full">
          <h2 class="text-center text-3xl">Select Sample DNA Code</h2>
          <p class="text-center text-gray-500">Click again to deselect</p>
          <div class="flex flex-wrap justify-center items-center gap-5 my-3">
            <div
              class="flex items-center justify-center select-none text-xl w-30 h-full border-2 border-gray-400 bg-gray-100 hover:bg-gray-200 rounded-2xl"
              :class="
                activeSample == 'cats'
                  ? 'bg-gray-300 hover:bg-gray-300'
                  : 'bg-gray-100'
              "
              @click="activateSample('cats')"
            >
              CATS
            </div>
            <div
              class="flex items-center justify-center select-none text-xl w-30 h-full border-2 border-gray-400 bg-gray-100 hover:bg-gray-200 rounded-2xl"
              :class="
                activeSample == 'dogs'
                  ? 'bg-gray-300 hover:bg-gray-300'
                  : 'bg-gray-100'
              "
              @click="activateSample('dogs')"
            >
              DOGS
            </div>
            <div
              class="flex items-center select-none justify-center text-xl w-30 h-full border-2 border-gray-400 bg-gray-100 hover:bg-gray-200 rounded-2xl"
              :class="
                activeSample == 'apples'
                  ? 'bg-gray-300 hover:bg-gray-300'
                  : 'bg-gray-100'
              "
              @click="activateSample('apples')"
            >
              APPLES
            </div>
            <div
              class="flex items-center select-none justify-center text-xl w-30 h-full border-2 border-gray-400 bg-gray-100 hover:bg-gray-200 rounded-2xl"
              :class="
                activeSample == 'humans'
                  ? 'bg-gray-300 hover:bg-gray-300'
                  : 'bg-gray-100'
              "
              @click="activateSample('humans')"
            >
              HUMANS
            </div>
          </div>
          <div class="text-center">
            <p>
              Sourced from:
              <a
                class="text-blue-500 hover:text-blue-700 underline"
                href="https://www.ncbi.nlm.nih.gov/"
                >https://www.ncbi.nlm.nih.gov/</a
              >
            </p>
          </div>
        </div>

        <!-- Textbox Input -->
        <div class="w-full text-center">
          <h2 class="text-center text-3xl">DNA Code</h2>
          <textarea
            v-model="dnaCode"
            placeholder="Type DNA sequence (A, C, T, G, N only)"
            class="w-full min-h-24 resize-y p-2 border rounded"
            @keydown="onKeyDown"
          />
          <p class="text-xs text-gray-500 mt-1">
            Only A, C, T, G, N (for unknown or no consensus) characters will be
            registered and all letters will be automatically capitalized.
          </p>
        </div>

        <!-- Additional Settings -->
        <div class="w-full text-center">
          <h2 class="text-2xl">Styling Options</h2>
          <div class="grid grid-cols-1">
            <!-- Colors -->
            <div>
              <h3 class="text-lg font-semibold mb-2">Colors</h3>
              <div class="grid grid-cols-5">
                <div class="flex items-center justify-center">
                  A : <input v-model="stylingSettings.colors.A" type="color" >
                </div>
                <div class="flex items-center justify-center">
                  C : <input v-model="stylingSettings.colors.C" type="color" >
                </div>
                <div class="flex items-center justify-center">
                  T : <input v-model="stylingSettings.colors.T" type="color" >
                </div>
                <div class="flex items-center justify-center">
                  G : <input v-model="stylingSettings.colors.G" type="color" >
                </div>
                <div class="flex items-center justify-center">
                  N (No Consensus) :
                  <input v-model="stylingSettings.colors.N" type="color" >
                </div>
              </div>
            </div>

            <!-- Barcode Width -->
            <div>
              <div class="flex flex-col items-center">
                <h3 class="text-lg font-semibold mb-2">Barcode Width</h3>
                <input
                  v-model="stylingSettings.width"
                  type="range"
                  min="5"
                  max="100"
                  class="w-full"
                >
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Output -->
      <div class="mt-5">
        <DNAVisual :dna-code="dnaCode" :options="stylingSettings" />
      </div>
    </div>
  </div>
</template>
