version: '3.8'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "65001:65001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=65001
